# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


stages:
  - stage:
    jobs:
       - job:
         pool: "Azure Pipelines"
         steps:
         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'spn1'
            subscriptionId: '003b772f-91e8-40ec-9470-b63ff9aac613'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'terraform_RG'
            location: 'East US'
            templateLocation: 'URL of the file'
            csmFileLink: 'https://github.com/EshaPersonal/subhoesha/blob/main/template.json'
            csmParametersFileLink: 'https://github.com/EshaPersonal/subhoesha/blob/main/parameters.json'
            deploymentMode: 'Complete'
            deploymentName: 'vm deployment'
            
