# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

variables: 
    - template : variable.yml
stages:
  - stage:
    jobs:
       - job:
         pool: "ubuntu-latest"
         steps:
            - script: echo "my favourite vegetable is ${{variables.favouriteveggies}}"
