name: yamldemo_$(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: ProjectName
    displayName: "Select Project Name to Build"
    type: string
    default: Payment
    values:
        - Payment
        - Profile
        - Admin
        - onlinepayment
  - name: EnvironmentType
    displayName: 'Select the Envionment'
    type: string
    default: QA
    values:
        - QA
        - Dev
        - Security

  - name: UnitTestRun
    displayName: 'Do you want to Run Unit Test?'
    type: boolean
    default: true

  - name: DeployCheck
    displayName: "Do you want to Deploy?"
    type: boolean
    default: true

trigger: none
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     name: default
    steps:
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          msbuildArgs: '/t:${{ parameters.ProjectName}}'
          platform: 'any cpu'
          configuration: 'release'
- ${{ if eq(parameters.UnitTestRun, true) }}:
  - stage: UnitTestRun
    jobs:
    - job: rununitest
      pool:
       name: default
      steps:
       - task: PowerShell@2
         inputs:
           targetType: 'inline'
           script: |
             # Write your PowerShell commands here.     
             Write-Host "Unit test Setup"
        
- ${{ if eq(parameters.DeployCheck, true) }}:
  - stage: Deploy
    jobs:
    - job: deployapp
      pool:
       name: default
      steps:
       - task: PowerShell@2
         inputs:
           targetType: 'inline'
           script: |
             # Write your PowerShell commands here.
             
             Write-Host "Deploy Setup.."